In [1]:
import pandas as pd
df=pd.read_csv('inputdata.csv')

In [2]:
df.head()

latitude  longitude  acc_x_dashboard  acc_y_dashboard  acc_z_dashboard  \
0 -27.717857 -51.098897         0.571221         0.192470         9.699378   
1 -27.717857 -51.098897         0.233639         0.771867        10.020201   
2 -27.717857 -51.098897         0.109141         0.479775         9.926827   
3 -27.717857 -51.098897         0.470665        -0.192996         9.553332   
4 -27.717857 -51.098897         0.518549         0.252325         9.814300   

   acc_x_above_suspension  acc_y_above_suspension  acc_z_above_suspension  \
0                0.352532                0.226281                9.770854   
1                0.115506                0.240646                9.894155   
2                0.383656                0.214310                9.117237   
3                0.802642               -0.228617                9.746912   
4                0.143039                0.375919                9.793599   

   acc_x_below_suspension  acc_y_below_suspension  ...  \
0                0.289128                0.131624  ...   
1                0.246033                0.034659  ...   
2                0.217302                0.193873  ...   
3                0.258004                0.122047  ...   
4                0.275960               -0.019211  ...   

   gyro_x_above_suspension  gyro_y_above_suspension  gyro_z_above_suspension  \
0                -0.655198                -0.739679                -0.588766   
1                 0.534988                 0.603094                 0.540384   
2                -0.136399                -0.159845                 0.357279   
3                -0.746750                -0.770197                -0.649801   
4                 0.306106                 0.282660                 0.280985   

   gyro_x_below_suspension  gyro_y_below_suspension  gyro_z_below_suspension  \
0                 0.388191                 0.124613                -0.186012   
1                -0.130608                 0.460307                -0.353859   
2                -0.191643                -0.150045                 0.271752   
3                 0.266121                -0.027974                 0.119164   
4                -0.100090                 0.673930                -0.430153   

      speed          road  quality  result  
0  0.023405  asphalt_road      3.0       2  
1  0.023405  asphalt_road      3.0       2  
2  0.023405  asphalt_road      3.0       2  
3  0.023405  asphalt_road      3.0       2  
4  0.023405  asphalt_road      3.0       2  

[5 rows x 24 columns]

In [3]:
df.rename(columns={'result': 'y_pred'}, inplace=True)

In [4]:
df.head()

latitude  longitude  acc_x_dashboard  acc_y_dashboard  acc_z_dashboard  \
0 -27.717857 -51.098897         0.571221         0.192470         9.699378   
1 -27.717857 -51.098897         0.233639         0.771867        10.020201   
2 -27.717857 -51.098897         0.109141         0.479775         9.926827   
3 -27.717857 -51.098897         0.470665        -0.192996         9.553332   
4 -27.717857 -51.098897         0.518549         0.252325         9.814300   

   acc_x_above_suspension  acc_y_above_suspension  acc_z_above_suspension  \
0                0.352532                0.226281                9.770854   
1                0.115506                0.240646                9.894155   
2                0.383656                0.214310                9.117237   
3                0.802642               -0.228617                9.746912   
4                0.143039                0.375919                9.793599   

   acc_x_below_suspension  acc_y_below_suspension  ...  \
0                0.289128                0.131624  ...   
1                0.246033                0.034659  ...   
2                0.217302                0.193873  ...   
3                0.258004                0.122047  ...   
4                0.275960               -0.019211  ...   

   gyro_x_above_suspension  gyro_y_above_suspension  gyro_z_above_suspension  \
0                -0.655198                -0.739679                -0.588766   
1                 0.534988                 0.603094                 0.540384   
2                -0.136399                -0.159845                 0.357279   
3                -0.746750                -0.770197                -0.649801   
4                 0.306106                 0.282660                 0.280985   

   gyro_x_below_suspension  gyro_y_below_suspension  gyro_z_below_suspension  \
0                 0.388191                 0.124613                -0.186012   
1                -0.130608                 0.460307                -0.353859   
2                -0.191643                -0.150045                 0.271752   
3                 0.266121                -0.027974                 0.119164   
4                -0.100090                 0.673930                -0.430153   

      speed          road  quality  y_pred  
0  0.023405  asphalt_road      3.0       2  
1  0.023405  asphalt_road      3.0       2  
2  0.023405  asphalt_road      3.0       2  
3  0.023405  asphalt_road      3.0       2  
4  0.023405  asphalt_road      3.0       2  

[5 rows x 24 columns]

In [5]:
value_mapping = {2: 'asphalt_road', 0: 'dirt_road', 1: 'cobblestone_road'}

# Use the map() function to apply the mapping to the column
df['y_pred'] = df['y_pred'].map(value_mapping)
df.head()

latitude  longitude  acc_x_dashboard  acc_y_dashboard  acc_z_dashboard  \
0 -27.717857 -51.098897         0.571221         0.192470         9.699378   
1 -27.717857 -51.098897         0.233639         0.771867        10.020201   
2 -27.717857 -51.098897         0.109141         0.479775         9.926827   
3 -27.717857 -51.098897         0.470665        -0.192996         9.553332   
4 -27.717857 -51.098897         0.518549         0.252325         9.814300   

   acc_x_above_suspension  acc_y_above_suspension  acc_z_above_suspension  \
0                0.352532                0.226281                9.770854   
1                0.115506                0.240646                9.894155   
2                0.383656                0.214310                9.117237   
3                0.802642               -0.228617                9.746912   
4                0.143039                0.375919                9.793599   

   acc_x_below_suspension  acc_y_below_suspension  ...  \
0                0.289128                0.131624  ...   
1                0.246033                0.034659  ...   
2                0.217302                0.193873  ...   
3                0.258004                0.122047  ...   
4                0.275960               -0.019211  ...   

   gyro_x_above_suspension  gyro_y_above_suspension  gyro_z_above_suspension  \
0                -0.655198                -0.739679                -0.588766   
1                 0.534988                 0.603094                 0.540384   
2                -0.136399                -0.159845                 0.357279   
3                -0.746750                -0.770197                -0.649801   
4                 0.306106                 0.282660                 0.280985   

   gyro_x_below_suspension  gyro_y_below_suspension  gyro_z_below_suspension  \
0                 0.388191                 0.124613                -0.186012   
1                -0.130608                 0.460307                -0.353859   
2                -0.191643                -0.150045                 0.271752   
3                 0.266121                -0.027974                 0.119164   
4                -0.100090                 0.673930                -0.430153   

      speed          road  quality        y_pred  
0  0.023405  asphalt_road      3.0  asphalt_road  
1  0.023405  asphalt_road      3.0  asphalt_road  
2  0.023405  asphalt_road      3.0  asphalt_road  
3  0.023405  asphalt_road      3.0  asphalt_road  
4  0.023405  asphalt_road      3.0  asphalt_road  

[5 rows x 24 columns]

In [8]:
pip install scipy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [7]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Compute accuracy
accuracy = accuracy_score(df['road'], df['y_pred'])
print("Accuracy:", accuracy)
report = classification_report(df['road'], df['y_pred'], output_dict=True)

precision_weighted_avg = report['weighted avg']['precision']
print("Precision: ", precision_weighted_avg)

recall_weighted_avg = report['macro avg']['recall']
print("Recall: ", recall_weighted_avg)

f1_score_weighted_avg = report['weighted avg']['f1-score']
print("F1-score: ", f1_score_weighted_avg)

# Compute confusion matrix
cm = confusion_matrix(df['road'], df['y_pred'])
print("Confusion Matrix:")
print(cm)

ModuleNotFoundError: No module named 'scipy.stats._boost.nct_ufunc'

In [8]:
df = df.drop('quality', axis=1)
df.columns

Index(['latitude', 'longitude', 'acc_x_dashboard', 'acc_y_dashboard',
       'acc_z_dashboard', 'acc_x_above_suspension', 'acc_y_above_suspension',
       'acc_z_above_suspension', 'acc_x_below_suspension',
       'acc_y_below_suspension', 'acc_z_below_suspension', 'gyro_x_dashboard',
       'gyro_y_dashboard', 'gyro_z_dashboard', 'gyro_x_above_suspension',
       'gyro_y_above_suspension', 'gyro_z_above_suspension',
       'gyro_x_below_suspension', 'gyro_y_below_suspension',
       'gyro_z_below_suspension', 'speed', 'road', 'y_pred'],
      dtype='object')

In [9]:
value_mapping = {'asphalt_road': 2, 'dirt_road': 0, 'cobblestone_road': 1}

# Use the map() function to apply the mapping to the column
df['y_pred'] = df['y_pred'].map(value_mapping)
df['road'] = df['road'].map(value_mapping)
df.head()

latitude  longitude  acc_x_dashboard  acc_y_dashboard  acc_z_dashboard  \
0 -27.717857 -51.098897         0.571221         0.192470         9.699378   
1 -27.717857 -51.098897         0.233639         0.771867        10.020201   
2 -27.717857 -51.098897         0.109141         0.479775         9.926827   
3 -27.717857 -51.098897         0.470665        -0.192996         9.553332   
4 -27.717857 -51.098897         0.518549         0.252325         9.814300   

   acc_x_above_suspension  acc_y_above_suspension  acc_z_above_suspension  \
0                0.352532                0.226281                9.770854   
1                0.115506                0.240646                9.894155   
2                0.383656                0.214310                9.117237   
3                0.802642               -0.228617                9.746912   
4                0.143039                0.375919                9.793599   

   acc_x_below_suspension  acc_y_below_suspension  ...  gyro_z_dashboard  \
0                0.289128                0.131624  ...         -0.149983   
1                0.246033                0.034659  ...          0.063640   
2                0.217302                0.193873  ...          0.063640   
3                0.258004                0.122047  ...          0.063640   
4                0.275960               -0.019211  ...          0.002605   

   gyro_x_above_suspension  gyro_y_above_suspension  gyro_z_above_suspension  \
0                -0.655198                -0.739679                -0.588766   
1                 0.534988                 0.603094                 0.540384   
2                -0.136399                -0.159845                 0.357279   
3                -0.746750                -0.770197                -0.649801   
4                 0.306106                 0.282660                 0.280985   

   gyro_x_below_suspension  gyro_y_below_suspension  gyro_z_below_suspension  \
0                 0.388191                 0.124613                -0.186012   
1                -0.130608                 0.460307                -0.353859   
2                -0.191643                -0.150045                 0.271752   
3                 0.266121                -0.027974                 0.119164   
4                -0.100090                 0.673930                -0.430153   

      speed  road  y_pred  
0  0.023405     2       2  
1  0.023405     2       2  
2  0.023405     2       2  
3  0.023405     2       2  
4  0.023405     2       2  

[5 rows x 23 columns]

In [ ]:
from sklearn.neighbors import KDTree
import numpy as np

In [23]:
coordinates = df[['latitude', 'longitude']].values
y_true = df['road'].values
y_pred = df['y_pred'].values
print(y_pred)

[2 2 2 ... 2 2 2]


In [24]:
radius = 0.002

In [25]:
kdtree = KDTree(coordinates)

(132492, 2)

In [26]:
def assign_majority_label(index):
    # Query KD-tree to find neighbors within radius
    neighbors_indices = kdtree.query_radius([coordinates[index]], r=radius)[0]
    
    print(neighbors_indices)
    
    # Extract labels of neighbors
    neighbor_labels = y_pred[neighbors_indices]
    
    print(neighbor_labels)
    
    # Determine majority label
    majority_label = np.bincount(neighbor_labels).argmax()
    
    print(majority_label)
    
    return majority_label

array([[-27.71785711, -51.09889668],
       [-27.71785711, -51.09889668],
       [-27.71785711, -51.09889668],
       ...,
       [-27.71780723, -51.0991075 ],
       [-27.71780723, -51.0991075 ],
       [-27.71780723, -51.0991075 ]])

In [ ]:
assigned_labels = [assign_majority_label(i) for i in range(len(coordinates))]

df['y_pred'] = assigned_labels

In [78]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Compute accuracy
accuracy = accuracy_score(df['road'], df['y_pred'])
print("Accuracy:", accuracy)
report = classification_report(df['road'], df['y_pred'], output_dict=True)

precision_weighted_avg = report['weighted avg']['precision']
print("Precision: ", precision_weighted_avg)

recall_weighted_avg = report['weighted avg']['recall']
print("Recall: ", recall_weighted_avg)

f1_score_weighted_avg = report['weighted avg']['f1-score']
print("F1-score: ", f1_score_weighted_avg)

# Compute confusion matrix
cm = confusion_matrix(df['road'], df['y_pred'])
print("Confusion Matrix:")
print(cm)

Accuracy: 0.7996482806509072
Precision: 0.7996482806509072
Recall: 0.7996482806509072
F1-score: 0.7996482806509072
Confusion Matrix:
[[ 1700 20472  1731]
 [ 4300 53328    42]
 [    0     0 50919]]
